default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ShopifyLoyaltyApp_development

test:
  <<: *default
  database: ShopifyLoyaltyApp_test

production:
  <<: *default
  database: ShopifyLoyaltyApp_production
  username: ShopifyLoyaltyApp
  password: <%= ENV['SHOPIFYLOYALTYAPP_DATABASE_PASSWORD'] %>
